# App
spring.application.name=auth-service
server.port=8081

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/flowboard_auth
spring.datasource.username=root
spring.datasource.password=Ch@m@n123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secret=flowboard_secret_key_must_be_at_least_256_bits_long_for_security
jwt.expiration=86400000